import 'package:flutter_activity_recognition/flutter_activity_recognition.dart';

class SensorsMeasurementEntity {
  double? rawAccMagnitudeStatsMean;
  double? rawAccMagnitudeStatsStd;
  double? rawAccMagnitudeStatsMoment3;
  double? rawAccMagnitudeStatsMoment4;
  double? rawAccMagnitudeStatsPercentile25;
  double? rawAccMagnitudeStatsPercentile50;
  double? rawAccMagnitudeStatsPercentile75;
  double? rawAcc3dMeanX;
  double? rawAcc3dMeanY;
  double? rawAcc3dMeanZ;
  double? rawAcc3dStdX;
  double? rawAcc3dStdY;
  double? rawAcc3dStdZ;
  double? rawAcc3dRoXy;
  double? rawAcc3dRoXz;
  double? rawAcc3dRoYz;
  double? procGyroMagnitudeStatsMean;
  double? procGyroMagnitudeStatsStd;
  double? procGyroMagnitudeStatsMoment3;
  double? procGyroMagnitudeStatsMoment4;
  double? procGyroMagnitudeStatsPercentile25;
  double? procGyroMagnitudeStatsPercentile50;
  double? procGyroMagnitudeStatsPercentile75;
  double? procGyro3dMeanX;
  double? procGyro3dMeanY;
  double? procGyro3dMeanZ;
  double? procGyro3dStdX;
  double? procGyro3dStdY;
  double? procGyro3dStdZ;
  double? procGyro3dRoXy;
  double? procGyro3dRoXz;
  double? procGyro3dRoYz;
  double? rawMagnetMagnitudeStatsMean;
  double? rawMagnetMagnitudeStatsStd;
  double? rawMagnetMagnitudeStatsMoment3;
  double? rawMagnetMagnitudeStatsMoment4;
  double? rawMagnetMagnitudeStatsPercentile25;
  double? rawMagnetMagnitudeStatsPercentile50;
  double? rawMagnetMagnitudeStatsPercentile75;
  double? rawMagnet3dMeanX;
  double? rawMagnet3dMeanY;
  double? rawMagnet3dMeanZ;
  double? rawMagnet3dStdX;
  double? rawMagnet3dStdY;
  double? rawMagnet3dStdZ;
  double? rawMagnet3dRoXy;
  double? rawMagnet3dRoXz;
  double? rawMagnet3dRoYz;
  double? rawMagnetAvrCosineSimilarityLagRange0;
  double? rawMagnetAvrCosineSimilarityLagRange1;
  double? rawMagnetAvrCosineSimilarityLagRange2;
  double? rawMagnetAvrCosineSimilarityLagRange3;
  double? rawMagnetAvrCosineSimilarityLagRange4;
  int? locationNumValidUpdates;
  double? locationLogLatitudeRange;
  double? locationLogLongitudeRange;
  double? locationMinAltitude;
  double? locationMaxAltitude;
  double? locationMinSpeed;
  double? locationMaxSpeed;
  double? locationBestHorizontalAccuracy;
  double? locationBestVerticalAccuracy;
  double? locationDiameter;
  double? locationLogDiameter;
  double? locationQuickFeaturesStdLat;
  double? locationQuickFeaturesStdLong;
  double? locationQuickFeaturesLatChange;
  double? locationQuickFeaturesLongChange;
  double? audioNaiveMfcc0Mean;
  double? audioNaiveMfcc1Mean;
  double? audioNaiveMfcc2Mean;
  double? audioNaiveMfcc3Mean;
  double? audioNaiveMfcc4Mean;
  double? audioNaiveMfcc5Mean;
  double? audioNaiveMfcc6Mean;
  double? audioNaiveMfcc7Mean;
  double? audioNaiveMfcc8Mean;
  double? audioNaiveMfcc9Mean;
  double? audioNaiveMfcc10Mean;
  double? audioNaiveMfcc11Mean;
  double? audioNaiveMfcc12Mean;
  double? audioNaiveMfcc0Std;
  double? audioNaiveMfcc1Std;
  double? audioNaiveMfcc2Std;
  double? audioNaiveMfcc3Std;
  double? audioNaiveMfcc4Std;
  double? audioNaiveMfcc5Std;
  double? audioNaiveMfcc6Std;
  double? audioNaiveMfcc7Std;
  double? audioNaiveMfcc8Std;
  double? audioNaiveMfcc9Std;
  double? audioNaiveMfcc10Std;
  double? audioNaiveMfcc11Std;
  double? audioNaiveMfcc12Std;
  double? audioPropertiesMaxAbsValue;
  double? audioPropertiesNormalizationMultiplier;
  bool? discreteAppStateIsActive;
  bool? discreteAppStateIsInactive;
  bool? discreteAppStateIsBackground;
  bool? discreteAppStateMissing;
  bool? discreteBatteryPluggedIsAc;
  bool? discreteBatteryPluggedIsUsb;
  bool? discreteBatteryPluggedIsWireless;
  bool? discreteBatteryPluggedMissing;
  bool? discreteBatteryStateIsUnknown;
  bool? discreteBatteryStateIsUnplugged;
  bool? discreteBatteryStateIsNotCharging;
  bool? discreteBatteryStateIsDischarging;
  bool? discreteBatteryStateIsCharging;
  bool? discreteBatteryStateIsFull;
  bool? discreteBatteryStateMissing;
  bool? discreteOnThePhoneIsFalse;
  bool? discreteOnThePhoneIsTrue;
  bool? discreteOnThePhoneMissing;
  bool? discreteRingerModeIsNormal;
  bool? discreteRingerModeIsSilentNoVibrate;
  bool? discreteRingerModeIsSilentWithVibrate;
  bool? discreteRingerModeMissing;
  bool? discreteWifiStatusIsNotReachable;
  bool? discreteWifiStatusIsReachableViaWifi;
  bool? discreteWifiStatusIsReachableViaWwan;
  bool? discreteWifiStatusMissing;
  /*double? lfMeasurementsLight;
  double? lfMeasurementsPressure;
  double? lfMeasurementsProximityCm;
  double? lfMeasurementsProximity;
  double? lfMeasurementsRelativeHumidity;*/
  double? lfMeasurementsBatteryLevel;
  double? lfMeasurementsScreenBrightness;
  //double? lfMeasurementsTemperatureAmbient;
  bool? discreteTimeOfDayBetween0and6;
  bool? discreteTimeOfDayBetween3and9;
  bool? discreteTimeOfDayBetween6and12;
  bool? discreteTimeOfDayBetween9and15;
  bool? discreteTimeOfDayBetween12and18;
  bool? discreteTimeOfDayBetween15and21;
  bool? discreteTimeOfDayBetween18and24;
  bool? discreteTimeOfDayBetween21and3;
  ActivityType? activityType;
  ActivityConfidence? activityConfidence;

  DateTime? timestamp;
  String? sessionId;

  //to json
  Map<String, dynamic> toJson() {
    return {
      'rawAccMagnitudeStatsMean': rawAccMagnitudeStatsMean,
      'rawAccMagnitudeStatsStd': rawAccMagnitudeStatsStd,
      'rawAccMagnitudeStatsMoment3': rawAccMagnitudeStatsMoment3,
      'rawAccMagnitudeStatsMoment4': rawAccMagnitudeStatsMoment4,
      'rawAccMagnitudeStatsPercentile25': rawAccMagnitudeStatsPercentile25,
      'rawAccMagnitudeStatsPercentile50': rawAccMagnitudeStatsPercentile50,
      'rawAccMagnitudeStatsPercentile75': rawAccMagnitudeStatsPercentile75,
      'rawAcc3dMeanX': rawAcc3dMeanX,
      'rawAcc3dMeanY': rawAcc3dMeanY,
      'rawAcc3dMeanZ': rawAcc3dMeanZ,
      'rawAcc3dStdX': rawAcc3dStdX,
      'rawAcc3dStdY': rawAcc3dStdY,
      'rawAcc3dStdZ': rawAcc3dStdZ,
      'rawAcc3dRoXy': rawAcc3dRoXy,
      'rawAcc3dRoXz': rawAcc3dRoXz,
      'rawAcc3dRoYz': rawAcc3dRoYz,
      'procGyroMagnitudeStatsMean': procGyroMagnitudeStatsMean,
      'procGyroMagnitudeStatsStd': procGyroMagnitudeStatsStd,
      /*'procGyroMagnitudeStatsMoment3': procGyroMagnitudeStatsMoment3,
      'procGyroMagnitudeStatsMoment4': procGyroMagnitudeStatsMoment4,
      'procGyroMagnitudeStatsPercentile25': procGyroMagnitudeStatsPercentile25,
      'procGyroMagnitudeStatsPercentile50': procGyroMagnitudeStatsPercentile50,
      'procGyroMagnitudeStatsPercentile75': procGyroMagnitudeStatsPercentile75,*/
      'procGyro3dMeanX': procGyro3dMeanX,
      'procGyro3dMeanY': procGyro3dMeanY,
      'procGyro3dMeanZ': procGyro3dMeanZ,
      'procGyro3dStdX': procGyro3dStdX,
      'procGyro3dStdY': procGyro3dStdY,
      'procGyro3dStdZ': procGyro3dStdZ,
      'procGyro3dRoXy': procGyro3dRoXy,
      'procGyro3dRoXz': procGyro3dRoXz,
      'procGyro3dRoYz': procGyro3dRoYz,
      'rawMagnetMagnitudeStatsMean': rawMagnetMagnitudeStatsMean,
      'rawMagnetMagnitudeStatsStd': rawMagnetMagnitudeStatsStd,
      'rawMagnetMagnitudeStatsMoment3': rawMagnetMagnitudeStatsMoment3,
      'rawMagnetMagnitudeStatsMoment4': rawMagnetMagnitudeStatsMoment4,
      'rawMagnetMagnitudeStatsPercentile25': rawMagnetMagnitudeStatsPercentile25,
      'rawMagnetMagnitudeStatsPercentile50': rawMagnetMagnitudeStatsPercentile50,
      'rawMagnetMagnitudeStatsPercentile75': rawMagnetMagnitudeStatsPercentile75,
      'rawMagnet3dMeanX': rawMagnet3dMeanX,
      'rawMagnet3dMeanY': rawMagnet3dMeanY,
      'rawMagnet3dMeanZ': rawMagnet3dMeanZ,
      'rawMagnet3dStdX': rawMagnet3dStdX,
      'rawMagnet3dStdY': rawMagnet3dStdY,
      'rawMagnet3dStdZ': rawMagnet3dStdZ,
      'rawMagnet3dRoXy': rawMagnet3dRoXy,
      'rawMagnet3dRoXz': rawMagnet3dRoXz,
      'rawMagnet3dRoYz': rawMagnet3dRoYz,
      'rawMagnetAvrCosineSimilarityLagRange0': rawMagnetAvrCosineSimilarityLagRange0,
      'rawMagnetAvrCosineSimilarityLagRange1': rawMagnetAvrCosineSimilarityLagRange1,
      'rawMagnetAvrCosineSimilarityLagRange2': rawMagnetAvrCosineSimilarityLagRange2,
      'rawMagnetAvrCosineSimilarityLagRange3': rawMagnetAvrCosineSimilarityLagRange3,
      'rawMagnetAvrCosineSimilarityLagRange4': rawMagnetAvrCosineSimilarityLagRange4,
      'locationNumValidUpdates': locationNumValidUpdates,
      'locationLogLatitudeRange': locationLogLatitudeRange,
      'locationLogLongitudeRange': locationLogLongitudeRange,
      'locationMinAltitude': locationMinAltitude,
      'locationMaxAltitude': locationMaxAltitude,
      'locationMinSpeed': locationMinSpeed,
      'locationMaxSpeed': locationMaxSpeed,
      'locationBestHorizontalAccuracy': locationBestHorizontalAccuracy,
      'locationBestVerticalAccuracy': locationBestVerticalAccuracy,
      'locationDiameter': locationDiameter,
      'locationLogDiameter': locationLogDiameter,
      'locationQuickFeaturesStdLat': locationQuickFeaturesStdLat == null || locationQuickFeaturesStdLat!.isNaN ? null : locationQuickFeaturesStdLat,
      'locationQuickFeaturesStdLong': locationQuickFeaturesStdLong == null || locationQuickFeaturesStdLong!.isNaN ? null : locationQuickFeaturesStdLong,
      'locationQuickFeaturesLatChange': locationQuickFeaturesLatChange == null || locationQuickFeaturesLatChange!.isNaN ? null : locationQuickFeaturesLatChange,
      'locationQuickFeaturesLongChange': locationQuickFeaturesLongChange == null || locationQuickFeaturesLongChange!.isNaN ? null : locationQuickFeaturesLongChange,
      'audioNaiveMfcc0Mean': audioNaiveMfcc0Mean,
      'audioNaiveMfcc1Mean': audioNaiveMfcc1Mean,
      'audioNaiveMfcc2Mean': audioNaiveMfcc2Mean,
      'audioNaiveMfcc3Mean': audioNaiveMfcc3Mean,
      'audioNaiveMfcc4Mean': audioNaiveMfcc4Mean,
      'audioNaiveMfcc5Mean': audioNaiveMfcc5Mean,
      'audioNaiveMfcc6Mean': audioNaiveMfcc6Mean,
      'audioNaiveMfcc7Mean': audioNaiveMfcc7Mean,
      'audioNaiveMfcc8Mean': audioNaiveMfcc8Mean,
      'audioNaiveMfcc9Mean': audioNaiveMfcc9Mean,
      'audioNaiveMfcc10Mean': audioNaiveMfcc10Mean,
      'audioNaiveMfcc11Mean': audioNaiveMfcc11Mean,
      'audioNaiveMfcc12Mean': audioNaiveMfcc12Mean,
      'audioNaiveMfcc0Std': audioNaiveMfcc0Std,
      'audioNaiveMfcc1Std': audioNaiveMfcc1Std,
      'audioNaiveMfcc2Std': audioNaiveMfcc2Std,
      'audioNaiveMfcc3Std': audioNaiveMfcc3Std,
      'audioNaiveMfcc4Std': audioNaiveMfcc4Std,
      'audioNaiveMfcc5Std': audioNaiveMfcc5Std,
      'audioNaiveMfcc6Std': audioNaiveMfcc6Std,
      'audioNaiveMfcc7Std': audioNaiveMfcc7Std,
      'audioNaiveMfcc8Std': audioNaiveMfcc8Std,
      'audioNaiveMfcc9Std': audioNaiveMfcc9Std,
      'audioNaiveMfcc10Std': audioNaiveMfcc10Std,
      'audioNaiveMfcc11Std': audioNaiveMfcc11Std,
      'audioNaiveMfcc12Std': audioNaiveMfcc12Std,
      'audioPropertiesMaxAbsValue': audioPropertiesMaxAbsValue,
      'audioPropertiesNormalizationMultiplier': audioPropertiesNormalizationMultiplier,
      'discreteAppStateIsActive': discreteAppStateIsActive,
      'discreteAppStateIsInactive': discreteAppStateIsInactive,
      'discreteAppStateIsBackground': discreteAppStateIsBackground,
      'discreteAppStateMissing': discreteAppStateMissing,
      'discreteBatteryPluggedIsAc': discreteBatteryPluggedIsAc,
      'discreteBatteryPluggedIsUsb': discreteBatteryPluggedIsUsb,
      'discreteBatteryPluggedIsWireless': discreteBatteryPluggedIsWireless,
      'discreteBatteryPluggedMissing': discreteBatteryPluggedMissing,
      'discreteBatteryStateIsUnknown': discreteBatteryStateIsUnknown,
      'discreteBatteryStateIsUnplugged': discreteBatteryStateIsUnplugged,
      'discreteBatteryStateIsNotCharging': discreteBatteryStateIsNotCharging,
      'discreteBatteryStateIsDischarging': discreteBatteryStateIsDischarging,
      'discreteBatteryStateIsCharging': discreteBatteryStateIsCharging,
      'discreteBatteryStateIsFull': discreteBatteryStateIsFull,
      'discreteBatteryStateMissing': discreteBatteryStateMissing,
      'discreteOnThePhoneIsFalse': discreteOnThePhoneIsFalse,
      'discreteOnThePhoneIsTrue': discreteOnThePhoneIsTrue,
      'discreteOnThePhoneMissing': discreteOnThePhoneMissing,
      'discreteRingerModeIsNormal': discreteRingerModeIsNormal,
      'discreteRingerModeIsSilentNoVibrate': discreteRingerModeIsSilentNoVibrate,
      'discreteRingerModeIsSilentWithVibrate': discreteRingerModeIsSilentWithVibrate,
      'discreteRingerModeMissing': discreteRingerModeMissing,
      'discreteWifiStatusIsNotReachable': discreteWifiStatusIsNotReachable,
      'discreteWifiStatusIsReachableViaWifi': discreteWifiStatusIsReachableViaWifi,
      'discreteWifiStatusIsReachableViaWwan': discreteWifiStatusIsReachableViaWwan,
      'discreteWifiStatusMissing': discreteWifiStatusMissing,
      /*'lfMeasurementsLight': lfMeasurementsLight,
      'lfMeasurementsPressure': lfMeasurementsPressure,
      'lfMeasurementsProximityCm': lfMeasurementsProximityCm,
      'lfMeasurementsProximity': lfMeasurementsProximity,
      'lfMeasurementsRelativeHumidity': lfMeasurementsRelativeHumidity,*/
      'lfMeasurementsBatteryLevel': lfMeasurementsBatteryLevel,
      'lfMeasurementsScreenBrightness': lfMeasurementsScreenBrightness,
      //'lfMeasurementsTemperatureAmbient': lfMeasurementsTemperatureAmbient,
      'discreteTimeOfDayBetween0and6': discreteTimeOfDayBetween0and6,
      'discreteTimeOfDayBetween3and9': discreteTimeOfDayBetween3and9,
      'discreteTimeOfDayBetween6and12': discreteTimeOfDayBetween6and12,
      'discreteTimeOfDayBetween9and15': discreteTimeOfDayBetween9and15,
      'discreteTimeOfDayBetween12and18': discreteTimeOfDayBetween12and18,
      'discreteTimeOfDayBetween15and21': discreteTimeOfDayBetween15and21,
      'discreteTimeOfDayBetween18and24': discreteTimeOfDayBetween18and24,
      'discreteTimeOfDayBetween21and3': discreteTimeOfDayBetween21and3,
      'activityType': activityType == ActivityType.IN_VEHICLE ? "IN_VEHICLE" :
        activityType == ActivityType.WALKING ? "WALKING" :
        activityType == ActivityType.RUNNING ? "RUNNING" :
        activityType == ActivityType.ON_BICYCLE ? "ON_BICYCLE" :
        null,
      'activityConfidence': activityConfidence?.index,
      'timestamp': timestamp?.millisecondsSinceEpoch,
      'sessionId': sessionId,
    };
  }
}